[train]
BLOCK_SIZE = 256
BATCH_SIZE = 8
MAX_ITERS = 3000
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.1
LOG_FREQ = 10

[data]
INPUT_FILE_PATH = "input.txt"

[output]
MODEL_PATH = "models/"
GRAPH_PATH = "analysis/"
