[train]
BLOCK_SIZE = 256
BATCH_SIZE = 8
MAX_ITERS = 3000
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.1
LOG_FREQ = 10
tokenizer = false
tokenizer_path = "tokenizers/tokenizer.json"
start_from_checkpoint = false
checkpoint_path = ""

[model]
n_layer = 6
n_embd = 256
dropout = 0.1
n_head = 4
mlp_internal_dim_multiplier = 128
vocab_size = 256

[data]
INPUT_FILE_PATH = "input.txt"

[output]
MODEL_PATH = "models/"
GRAPH_PATH = "analysis/"

[tokenizer]
INPUT_TEXT = "input.txt"
OUTPUT_PATH = "tokenizers/tokenizer.json"
VOCAB_SIZE = 32_000
SPECIAL_TOKENS = ["<pad>", "<unk>", "<bos>", "<eos>"]
